import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// SPA Navigation fallback: serve index.html for all page requests (like /patient-portal) when offline
try {
  const handler = createHandlerBoundToURL('/index.html');
  const navigationRoute = new NavigationRoute(handler, {
    denylist: [
      new RegExp('^/api/'),
      new RegExp('^/actuator/')
    ]
  });
  registerRoute(navigationRoute);
} catch (e) {
  console.log('Error registering NavigationRoute', e);
}

// Listen for Push Events from the Backend
self.addEventListener('push', function(event) {
  if (event.data) {
    try {
      const data = event.data.json();
      const options = {
        body: data.body,
        icon: '/icon-192.png',
        badge: '/icon-192.png',
        vibrate: [200, 100, 200, 100, 200, 100, 200], // Aggressive vibration pattern
        requireInteraction: true, // Forces it to stay on screen until dismissed
        renotify: true, // Forces sound/vibration even if there is already an existing notification
        tag: 'urgent-call', // Required for renotify
        silent: false, // Ensures sound is not suppressed
        data: {
          url: data.url || '/'
        }
      };

      event.waitUntil(
        self.registration.showNotification(data.title, options)
      );
    } catch (err) {
      console.error('Error parsing push data', err);
      event.waitUntil(
        self.registration.showNotification('HealthTech Alert', {
          body: event.data.text(),
          icon: '/icon-192.png'
        })
      );
    }
  }
});

// Handle Notification Clicks (e.g., open the app)
self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  
  const urlToOpen = event.notification.data.url;

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(windowClients) {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, open a new window
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});

// Background Sync (Offline Support)
self.addEventListener('sync', function(event) {
  if (event.tag === 'sync-queue') {
    console.log('[Service Worker] Background Sync Triggered: sync-queue');
    // In a full implementation, you would read from IndexedDB and replay failed requests
  }
});
