export const APP_STATUS = {
    WAITING: "WAITING",
    ARRIVED: "ARRIVED",
    DELAYED: "DELAYED",
    LATE: "LATE",
    CHECKED_IN: "CHECKED_IN",
    IN_SESSION: "IN_SESSION",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
    NO_SHOW: "NO_SHOW"
} as const;

export const APP_ROLES = {
    PATIENT: "ROLE_PATIENT",
    DOCTOR: "ROLE_DOCTOR",
    MEDIATOR: "ROLE_MEDIATOR"
} as const;

export const APP_TIERS = {
    PREMIUM: "PREMIUM",
    FREE: "FREE"
} as const;

export const ACTIVE_QUEUE_STATUSES = [
    APP_STATUS.WAITING, APP_STATUS.ARRIVED, APP_STATUS.DELAYED, 
    APP_STATUS.LATE, APP_STATUS.CHECKED_IN, APP_STATUS.IN_SESSION
];
